Repository canonical/partners.ubuntu.com, pull requests merged in 2018-08, with the labels that each got.

#160 159: Update IBM partners page
  static/sass/_partners-card.scss
  static/sass/styles.scss
  templates/partner.html
  templates/templates/_ibm-card.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#163 Remove old styling and add Vanilla Framework 1.8. NOTE: all pages will have broken styling.
  package.json
  static/sass/_partners-card.scss
  static/sass/core-constants.scss
  static/sass/core-mixins.scss
  static/sass/core-print.scss
  static/sass/ie/ie6.scss
  static/sass/ie/ie7.scss
  static/sass/ie/ie8.scss
  static/sass/styles.scss
  templates/templates/base.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#164 Add global nav, stock Vanilla navigation and first pass of homepage
  package.json
  static/js/scratch.js
  static/sass/styles.scss
  templates/index.html
  templates/templates/_contextual-footer.html
  templates/templates/base.html
  templates/templates/footer.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#165 Update contact and thank you pages
  templates/contact-us.html
  templates/thank-you.html
Labels: Review: Code +1, Review: QA +1

#166 Update run script
  .gitignore
  .sass-lint.yml
  package.json
  run
Labels: Review: Code +1, Review: QA +1

#167 Partnering with us
  templates/index.html
  templates/partnering-with-us/index.html
  templates/templates/_contextual-footer.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#169 Partner programmes page update
  templates/admin/base.html
  templates/programmes/_nav_secondary.html
  templates/programmes/index.html
  templates/templates/_nav_breadcrumb.html
  templates/templates/base.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#170 Update public cloud page. Make ticks orange and tweak programmes markup.
  static/sass/styles.scss
  templates/block/_logo-list.html
  templates/programmes/index.html
  templates/programmes/public-cloud.html
  templates/templates/_contextual-footer.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#171 Update openstack page
  templates/programmes/openstack.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#173 Update software page
  templates/programmes/software.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#176 Channel
  templates/programmes/channel.html
  templates/programmes/charm.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#168 Fixes typo and stray word
  templates/templates/_contextual-footer.html
Labels: Review: Code +1, Review: QA +1

#175 Retail
  templates/programmes/retail.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#174 Hardware
  templates/programmes/hardware.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#177 Update IoT page
  templates/programmes/hardware.html
  templates/programmes/iot.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#180 Fix CMS object name bug, return string in addition to unicode object names
  cms/models.py
Labels: Review: Code +1, Review: QA +1
