Repository canonical/partners.ubuntu.com, pull requests merged in 2020-07, with the labels that each got.

#252 Move deployment configs into the repo
  .env
  .gitignore
  deploy/site.yaml
  package.json
Labels: Review: Code +1, Review: QA +1

#253 Switch around name and key in DB secret
  deploy/site.yaml
Labels: Review: Code +1

#254 The partners app needs 512MiB RAM to run
  .dockerignore
  Dockerfile
  deploy/site.yaml
Labels: Review: Code +1, Review: QA +1

#256 Rename deploy to konf
  konf/site.yaml
Labels: Review: QA +1
